# grafana.docker-compose.yml

version: '3.9'

services:
  grafana:
    # container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-grafana}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=${GRAFANA_USERS_ALLOW_SIGN_UP:-false}
    ports:
      - "3000:3000"
    volumes:
      - ~/projects/ttrpg/volume-mounts/grafana:/var/lib/grafana
      - ~/projects/ttrpg/ttrpg-api/image/grafana/provisioning:/etc/grafana/provisioning
