apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-master-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # TODO: verify this
