apiVersion: v1
kind: Service
metadata:
  name: postgresql-master
spec:
  selector:
    app: postgresql-master
  ports:
    - port: 5432
      targetPort: 5432
  # Add service annotations if needed (for example, for external access)
