apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-replica-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
