default_language_version:
  python: python3.10

default_stages: [commit, push]

fail_fast: true

repos:
  # BUILT INTS
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
        exclude: "test_data/json/seeds"
        args: ['--maxkb=500']
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ['--autofix', '--indent=2', '--no-sort-keys']
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
        args: [--branch, staging]
      - id: trailing-whitespace

  # PYUPGRADE
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  # BLACK
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  # ISORT
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # AUTOFLAKE
  - repo: https://github.com/myint/autoflake
    rev: "v1.7.7"
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        "types": [python]
        require_serial: true
        args:
          - "--in-place"
          - "--expand-star-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
          - "--remove-all-unused-imports"
          # - --recursive
          # - --exclude
          # - __init__.py

  # FLAKE8
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        additional_dependencies:
          [
            # "flake8-bugbear==19.8.0",
            # "flake8-coding==1.3.2",
            "flake8-comprehensions==3.0.1",
            "flake8-debugger==3.2.1",
            "flake8-deprecated==1.3",
            "flake8-docstrings==1.5.0",
            # # "flake8-isort==2.7.0",
            "flake8-pep3101==1.2.1",
            "flake8-polyfill==1.0.2",
            "flake8-print==3.1.4",
            # "flake8-quotes==2.1.1",
            "flake8-string-format==0.2.3",
          ]

  # PYLINT [TODO: fix errors]
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.5
    hooks:
      - id: pylint
        args:
          - --max-line-length=120
          - --ignore-imports=yes
          - -d duplicate-code

  # PYGREP-HOOKS
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  # MYPY
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
      - id: mypy
        exclude: tests/|alembic/|scripts/
        args:
          [
            --disallow-untyped-defs,
            --check-untyped-defs,
            --warn-redundant-casts,
            --no-implicit-optional,
            --strict-optional,
          ]

  # Other commmit hooks (best-doctor)
  - repo: https://github.com/best-doctor/pre-commit-hooks
    rev: v1.0.11
    hooks:
    - id: mccabe-complexity
      name: Check functions complexity (mccabe)
      language: python
    - id: expr-complexity
      name: Check expressions complexity
      exclude: /samples/
      language: python
    - id: no-asserts
      name: Check no asserts in code
      language: python
      exclude: /tests/
    - id: test-naming
      name: Check if tests named appropriately
      language: python
    # - id: line-count
    #   name: Check number of lines in python files
    #   language: python
    - id: old-style-annotations
      name: Check old-style annotations
      language: python
