"""init.

Revision ID: 000d4966720d
Revises:
Create Date: 2024-11-03 07:21:23.829257

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "000d4966720d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Database migration: upgrade."""
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_system",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_system")),
        sa.UniqueConstraint("name", "version", "release_year", name=op.f("uq_game_system_name")),
        schema="event_planning",
    )
    op.create_index(
        op.f("ix_event_planning_game_system_id"), "game_system", ["id"], unique=False, schema="event_planning"
    )
    op.create_index(
        op.f("ix_event_planning_game_system_updated_at"),
        "game_system",
        ["updated_at"],
        unique=False,
        schema="event_planning",
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("profile_picture_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        schema="event_planning",
    )
    op.create_index(op.f("ix_event_planning_user_id"), "user", ["id"], unique=False, schema="event_planning")
    op.create_table(
        "game_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_system_id", sa.UUID(), nullable=False),
        sa.Column("game_master_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("max_players", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("image_url_description", sa.String(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_master_id"], ["event_planning.user.id"], name=op.f("fk_game_session_game_master_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["game_system_id"],
            ["event_planning.game_system.id"],
            name=op.f("fk_game_session_game_system_id_game_system"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_session")),
        schema="event_planning",
    )
    op.create_index(
        op.f("ix_event_planning_game_session_id"), "game_session", ["id"], unique=False, schema="event_planning"
    )
    op.create_index(
        op.f("ix_event_planning_game_session_updated_at"),
        "game_session",
        ["updated_at"],
        unique=False,
        schema="event_planning",
    )
    op.create_table(
        "jt_user_game_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("game_session_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["event_planning.game_session.id"],
            name=op.f("fk_jt_user_game_session_game_session_id_game_session"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["event_planning.user.id"], name=op.f("fk_jt_user_game_session_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jt_user_game_session")),
        schema="event_planning",
    )
    op.create_index(
        op.f("ix_event_planning_jt_user_game_session_id"),
        "jt_user_game_session",
        ["id"],
        unique=False,
        schema="event_planning",
    )
    op.create_index(
        op.f("ix_event_planning_jt_user_game_session_updated_at"),
        "jt_user_game_session",
        ["updated_at"],
        unique=False,
        schema="event_planning",
    )
    # ### end Alembic commands ###

    post_upgrade()


def downgrade() -> None:
    """Database migration: downgrade."""
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_event_planning_jt_user_game_session_updated_at"),
        table_name="jt_user_game_session",
        schema="event_planning",
    )
    op.drop_index(
        op.f("ix_event_planning_jt_user_game_session_id"), table_name="jt_user_game_session", schema="event_planning"
    )
    op.drop_table("jt_user_game_session", schema="event_planning")
    op.drop_index(
        op.f("ix_event_planning_game_session_updated_at"), table_name="game_session", schema="event_planning"
    )
    op.drop_index(op.f("ix_event_planning_game_session_id"), table_name="game_session", schema="event_planning")
    op.drop_table("game_session", schema="event_planning")
    op.drop_index(op.f("ix_event_planning_user_id"), table_name="user", schema="event_planning")
    op.drop_table("user", schema="event_planning")
    op.drop_index(op.f("ix_event_planning_game_system_updated_at"), table_name="game_system", schema="event_planning")
    op.drop_index(op.f("ix_event_planning_game_system_id"), table_name="game_system", schema="event_planning")
    op.drop_table("game_system", schema="event_planning")
    # ### end Alembic commands ###

    post_downgrade()


def pre_upgrade() -> None:
    """Processing before upgrading the schema."""


def post_upgrade() -> None:
    """Processing after upgrading the schema."""


def pre_downgrade() -> None:
    """Processing before downgrading the schema."""


def post_downgrade() -> None:
    """Processing after downgrading the schema."""
