"""init.

Revision ID: a9e1db19b066
Revises:
Create Date: 2024-09-20 19:30:43.748297

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9e1db19b066"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    """Database migration: upgrade."""
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_session",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("organizer", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_session")),
        schema="event_planning",
    )
    op.create_index(
        op.f("ix_event_planning_game_session_id"), "game_session", ["id"], unique=False, schema="event_planning"
    )
    op.create_index(
        op.f("ix_event_planning_game_session_updated_at"),
        "game_session",
        ["updated_at"],
        unique=False,
        schema="event_planning",
    )
    # ### end Alembic commands ###

    post_upgrade()


def downgrade():
    """Database migration: downgrade."""
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_event_planning_game_session_updated_at"), table_name="game_session", schema="event_planning"
    )
    op.drop_index(op.f("ix_event_planning_game_session_id"), table_name="game_session", schema="event_planning")
    op.drop_table("game_session", schema="event_planning")
    # ### end Alembic commands ###

    post_downgrade()


def pre_upgrade():
    """Processing before upgrading the schema."""


def post_upgrade():
    """Processing after upgrading the schema."""


def pre_downgrade():
    """Processing before downgrading the schema."""


def post_downgrade():
    """Processing after downgrading the schema."""
