version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: image/Dockerfile
      target: development
      # target: prodcution
    container_name: dnd-api
    env_file:
      - ../.env
    environment:
      # override connection to localhost with host.docker.internal
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:admin@host.docker.internal:5432/ttrpg-pg
      - SQLALCHEMY_TESTING_DATABASE_URI=postgresql://postgres:admin@host.docker.internal:5433/ttrpg-pg
    ports:
      - '8001:8001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
    depends_on:
      - postgresql # see ROOT/image/postgres/docker-compose.yml
      # optional: grafana
      # optional: prometheus
