# Dockerfile
# Uses multi-stage builds requiring Docker 17.05 or higher
# See https://docs.docker.com/develop/develop-images/multistage-build/

################################################################################
# python-base
#    Creating a python base with shared environment variables
################################################################################
FROM python:3.12.2-slim AS python-base

WORKDIR /tmp

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1
    # PIP_NO_CACHE_DIR=off \
    # PIP_DISABLE_PIP_VERSION_CHECK=on \
    # PIP_DEFAULT_TIMEOUT=100 \
    # POETRY_HOME="/opt/poetry" \
    # POETRY_VIRTUALENVS_IN_PROJECT=true \
    # POETRY_NO_INTERACTION=1 \
    # PYSETUP_PATH="/opt/pysetup" \
    # VENV_PATH="/opt/pysetup/.venv"

# Poetry
RUN pip install poetry
COPY ./pyproject.toml ./poetry.lock* /tmp/
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

################################################################################
# builder-base
#    'builder-base' stage is used to build dependencies
#    python3-dev, libpq-dev -> required for psycopg2
################################################################################
FROM python-base AS builder-base

WORKDIR /code

RUN buildDeps="build-essential" \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        curl \
        vim \
        python3-dev \
        libpq-dev \
        gcc \
    && apt-get install -y --no-install-recommends $buildDeps \
    && rm -rf /var/lib/apt/lists/*


################################################################################
# development
#    'development' stage installs all dev deps and can be used to develop code.
#    For example using docker-compose to mount local volume under /app
################################################################################
FROM python-base as development
ENV FASTAPI_ENV=production

WORKDIR /code

COPY --from=builder-base /tmp/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY . /code/app

# Copying in our entrypoint
COPY docker-entrypoint.sh /code/docker-entrypoint.sh
RUN chmod +x /code/docker-entrypoint.sh

EXPOSE 8001
ENTRYPOINT /code/docker-entrypoint.sh $0 $@

# poetry run uvicorn --host=127.0.0.1 --port=8001 dnd.main:app
CMD ["uvicorn", "--reload", "--host=0.0.0.0", "--port=8001", "dnd.main:app"]

################################################################################
# lint (development)
#    'lint' stage runs black and isort
#    running in check mode means build will fail if any linting errors occur
################################################################################

FROM development AS lint
RUN black --config ./pyproject.toml --check app tests
RUN isort --settings-path ./pyproject.toml --recursive --check-only
CMD ["tail", "-f", "/dev/null"]

################################################################################
# test (development)
#    'test' stage runs our unit tests with pytest and
#    coverage.  Build will fail if test coverage is under 95%
################################################################################
FROM development AS test
RUN coverage run --rcfile ./pyproject.toml -m pytest ./tests
RUN coverage report --fail-under 95
