version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: development
      # target: prodcution
    container_name: dnd-api
    env_file:
      - ../.env
    environment:
      # override connection to localhost with host.docker.internal
      - POSTGRES_DATABASE_URI=postgresql://postgres:admin@host.docker.internal:5432/ttrpg-pg
      - POSTGRES_TESTING_DATABASE_URI=postgresql://postgres:admin@host.docker.internal:5433/ttrpg-pg
    ports:
      - '8001:8001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
    depends_on:
<<<<<<< HEAD:pydnd/image/docker-compose.yml
      - postgresql # see ROOT/image/postgres/docker-compose.yml
      # optional: grafana
      # optional: prometheus
=======
      - postgresql # see ROOT/deploy/postgres.docker-compose.yml
>>>>>>> fc70bdc (DND-46/47 feature(dnd,event-planning) Init D&D spells, Init event-planning):pydnd/deploy/docker-compose.yml
