# prometheus.docker-compose.yml

version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    # Mount the local Prometheus configuration file
    volumes:
      - ~/projects/ttrpg/ttrpg-api/image/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    # Command to start Prometheus with the specified configuration file
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
