"""init.

Revision ID: eae6cb7f388f
Revises:
Create Date: 2022-11-20 11:32:21.517182

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eae6cb7f388f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Init: upgrade db to this version."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("short_name"),
        schema="dnd",
    )
    op.create_index(op.f("ix_dnd_source_id"), "source", ["id"], unique=False, schema="dnd")
    op.create_table(
        "dnd_class",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("hit_die", sa.String(), nullable=False),
        sa.Column("primary_ability", sa.String(), nullable=False),
        sa.Column("saving_throw_proficiencies", sa.String(), nullable=False),
        sa.Column("armor_proficiencies", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("shield_proficiencies", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("weapon_proficiencies", sa.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["dnd.source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="dnd",
    )
    op.create_index(op.f("ix_dnd_dnd_class_id"), "dnd_class", ["id"], unique=False, schema="dnd")
    op.create_table(
        "spell",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("casting_time", sa.String(), nullable=False),
        sa.Column("classes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("components", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("duration", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("range", sa.String(), nullable=False),
        sa.Column("ritual", sa.Boolean(), nullable=False),
        sa.Column(
            "school",
            sa.Enum(
                "ABJURATION",
                "CONJURATION",
                "DIVININATION",
                "ENCHANTMENT",
                "ILLUSION",
                "EVOCATION",
                "NECROMANCY",
                "TRANSMUTATION",
                name="spellschoolenum",
                schema="dnd",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.Column("homebrew", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["dnd.source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dnd",
    )
    op.create_index(op.f("ix_dnd_spell_id"), "spell", ["id"], unique=False, schema="dnd")
    op.create_index(
        op.f("ix_dnd_spell_updated_at"),
        "spell",
        ["updated_at"],
        unique=False,
        schema="dnd",
    )
    op.create_table(
        "jt_spell_to_class",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("spell_id", sa.Integer(), nullable=True),
        sa.Column("dnd_class_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dnd_class_id"],
            ["dnd.dnd_class.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["dnd.source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["spell_id"],
            ["dnd.spell.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dnd",
    )
    op.create_index(
        op.f("ix_dnd_jt_spell_to_class_id"),
        "jt_spell_to_class",
        ["id"],
        unique=False,
        schema="dnd",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Init: downgrade db to previous version (completely remove schema)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dnd_jt_spell_to_class_id"),
        table_name="jt_spell_to_class",
        schema="dnd",
    )
    op.drop_table("jt_spell_to_class", schema="dnd")
    op.drop_index(op.f("ix_dnd_spell_updated_at"), table_name="spell", schema="dnd")
    op.drop_index(op.f("ix_dnd_spell_id"), table_name="spell", schema="dnd")
    op.drop_table("spell", schema="dnd")
    op.drop_index(op.f("ix_dnd_dnd_class_id"), table_name="dnd_class", schema="dnd")
    op.drop_table("dnd_class", schema="dnd")
    op.drop_index(op.f("ix_dnd_source_id"), table_name="source", schema="dnd")
    op.drop_table("source", schema="dnd")
    # ### end Alembic commands ###
