################################################################################
# Site metadata ###
################################################################################

site_name: Dungeons & Dragons API
site_description: Documentation for the DnD API
# site_url: N/A

repo_url: https://github.com/humoroushorse/dnd-api
edit_uri: edit/main/pydnd/docs

################################################################################
# Build settings
################################################################################

# theme: readthedocs
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Tutorial:
    # - TL;DR: tutorial/tldr.md
    # - Installation: tutorial/installation.md
    # - Set up project: tutorial/setup-project.md
    # - Advanced: tutorial/advanced.md
    # - Usage: tutorial/usage.md
    # - Deploy: tutorial/deploy.md
    - Adding a Table: tutorial/adding_a_table.md
    - Alembic: tutorial/alembic.md
    - Testing: tutorial/testing.md
  - Code:
    - API:
      - API Module: code/api-module.md
      - Endpoints:
        - /classes: code/endpoints/classes.md
        - /sources: code/endpoints/sources.md
        - /spell-to-class: code/endpoints/spell-to-class.md
        - /spells: code/endpoints/spells.md
    - Core Module: code/core-module.md
    - Database Module: code/database-module.md
    - Models Module: code/models-module.md
    - Repository Module: code/repository-module.md
    - Schemas Module: code/schemas-module.md
