
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttrpg-api-event-planning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttrpg-api-event-planning
  template:
    metadata:
      labels:
        app: ttrpg-api-event-planning
    spec:
      containers:
      - name: ttrpg-api-event-planning
        image: localhost:5001/ttrpg-api/py_event_planning:latest
        imagePullPolicy: IfNotPresent # this is a local image
        ports:
        - containerPort: 8002
