version: '3.9'

services:
  ttrpg-api-event-planning:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: development
      # target: prodcution
    container_name: ttrpg-api-event-planning
    env_file:
      - ../.env
    environment:
      # override connection to localhost with host.docker.internal
      - POSTGRES_DATABASE_URI=postgresql+asyncpg://postgres:admin@postgresql:5432/ttrpg-pg
      - KEYCLOAK_SERVER_URL=http://keycloak:8080/
      # - KEYCLOAK_REALM_NAME=ttrpg
      # - KEYCLOAK_CLIENT_ID=ttrpg-client
      - KEYCLOAK_REALM_NAME=master
      - KEYCLOAK_CLIENT_ID=admin-cli
    ports:
      - '8002:8002'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/backend:/logs
    # restart: "no"
    # depends_on:
    #   - postgresql # see ROOT/deploy/postgres/postgres.compose.yml
    #   - keycloak # see ROOT/deploy/keycloak/keycloak.compose.yml
